version: '3.0'

services:
  ros_core:
    container_name: ros_core
    build: .
    # Image name for consistency
    image: ros:noetic-ros-base

    # Bind host directory to container dir
    volumes:
      - ../catkin_ws:/opt/catkin_ws
      - ./ros_env_init.sh:/opt/ros_env_init.sh
    environment:
      - DISPLAY=${DISPLAY}
      # Allow containers to run in background
    command: bash -c "tail -F anything"

    network_mode: host

volumes:
  ros_node:
