version: '3.7'

services:
  ros_core:
    container_name: ros_core
    build: .
    # Image name for consistency
    image: ros:noetic-ros-base

    # Bind host directory to container dir
    volumes:
      - ../cat2/:/opt/cat2
      - ../catkin_ws:/opt/catkin_ws
      - ./ros_env_init.sh:/opt/ros_env_init.sh
      - ~/repos/PySticks:/opt/PySticks

    devices:
      - /dev/tty:/dev/tty
    environment:
      - DISPLAY=${DISPLAY}
      # Allow containers to run in background
    command: "tail -F anything"
    init: true
    network_mode: host

volumes:
  ros_node:
